### Recursive Feature Selection

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [ ]:
X.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(X,y)

RandomForestClassifier()

In [ ]:
rf.feature_importances_

array([0.10202703, 0.0229681 , 0.4550667 , 0.41993816])

In [ ]:
X.drop(columns='sepal_width',inplace=True)
X.head()

   sepal_length  petal_length  petal_width
0           5.1           1.4          0.2
1           4.9           1.4          0.2
2           4.7           1.3          0.2
3           4.6           1.5          0.2
4           5.0           1.4          0.2

In [ ]:
rf = RandomForestClassifier()
rf.fit(X,y)

rf.feature_importances_

array([0.20648351, 0.44262499, 0.3508915 ])

In [ ]:
X.drop(columns='sepal_length',inplace=True)
X.head()

   petal_length  petal_width
0           1.4          0.2
1           1.4          0.2
2           1.3          0.2
3           1.5          0.2
4           1.4          0.2

In [ ]:
rf = RandomForestClassifier()
rf.fit(X,y)

rf.feature_importances_

array([0.4495768, 0.5504232])

In [ ]:
X.drop(columns='petal_length',inplace=True)
X.head()

   petal_width
0          0.2
1          0.2
2          0.2
3          0.2
4          0.2

### Sklearn RFE

In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Load iris dataset
url = "https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
df = pd.read_csv(url)

# Separate features and target variable
X = df.drop("species", axis=1)
y = df["species"]

# Initialize RandomForestClassifier
model = RandomForestClassifier()

# Initialize RFE
rfe = RFE(estimator=model, n_features_to_select=1)

# Fit RFE
rfe.fit(X, y)

# Print the ranking
ranking = rfe.ranking_
print("Feature ranking:")

for i, feature in enumerate(X.columns):
    print(f"{feature}: {ranking[i]}")

Feature ranking:
sepal_length: 3
sepal_width: 4
petal_length: 2
petal_width: 1